# Generated by Django 2.2.3 on 2019-09-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='beast',
            new_name='fantasticbeast',
        ),
    ]
